CREATE TABLE Roles (
    RoleID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RoleName VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE VehicleModels (
    ModelID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Brand VARCHAR2(100),
    ModelName VARCHAR2(100) NOT NULL,
    MaxSpeedKMH NUMBER,
    WeightLimitKG NUMBER,
    VehicleType VARCHAR2(20) CHECK (VehicleType IN ('самокат', 'велосипед'))
);

CREATE TABLE Tariffs (
    TariffID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(50) NOT NULL,
    UnlockPrice NUMBER(10, 2) NOT NULL,
    MinutePrice NUMBER(10, 2) NOT NULL,
    IsActive NUMBER(1) DEFAULT 1 CHECK (IsActive IN (0, 1))
);

CREATE TABLE Users (
    UserID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FullName VARCHAR2(255) NOT NULL,
    Email VARCHAR2(100) NOT NULL UNIQUE,
    Phone VARCHAR2(20) NOT NULL UNIQUE,
    Balance NUMBER(10, 2) DEFAULT 0.00 CHECK (Balance >= 0),
    RoleID NUMBER NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_User_Role FOREIGN KEY (RoleID) REFERENCES Roles(RoleID)
);

CREATE TABLE Vehicles (
    VehicleID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    QRCode VARCHAR2(50) NOT NULL UNIQUE,
    ModelID NUMBER NOT NULL,
    TariffID NUMBER NOT NULL,
    BatteryLevel NUMBER DEFAULT 100 CHECK (BatteryLevel BETWEEN 0 AND 100),
    Status VARCHAR2(20) DEFAULT 'доступно' 
        CHECK (Status IN ('доступно', 'бронь', 'ремонт', 'зарядка', 'сломано')),
    Lat NUMBER(9, 6),
    Lon NUMBER(9, 6),
    LastServiceDate TIMESTAMP,
    CONSTRAINT FK_Vehicle_Model FOREIGN KEY (ModelID) REFERENCES VehicleModels(ModelID),
    CONSTRAINT FK_Vehicle_Tariff FOREIGN KEY (TariffID) REFERENCES Tariffs(TariffID)
);

CREATE TABLE Rentals (
    RentalID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    UserID NUMBER NOT NULL,
    VehicleID NUMBER NOT NULL,
    StartTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EndTime TIMESTAMP,
    FixedMinutePrice NUMBER(10, 2) NOT NULL,
    TotalCost NUMBER(10, 2),
    RentalStatus VARCHAR2(20) DEFAULT 'активно' 
        CHECK (RentalStatus IN ('активно', 'завершено', 'отменено')),
    CONSTRAINT FK_Rental_User FOREIGN KEY (UserID) REFERENCES Users(UserID),
    CONSTRAINT FK_Rental_Vehicle FOREIGN KEY (VehicleID) REFERENCES Vehicles(VehicleID)
);



CREATE INDEX IX_Users_Email ON Users(Email);

CREATE VIEW AvailableVehicles AS
SELECT v.VehicleID, v.QRCode, m.Brand, m.ModelName, t.MinutePrice, v.BatteryLevel, v.Lat, v.Lon
FROM Vehicles v
JOIN VehicleModels m ON v.ModelID = m.ModelID
JOIN Tariffs t ON v.TariffID = t.TariffID
WHERE v.Status = 'доступно';

CREATE SEQUENCE ContractNumber START WITH 1000 INCREMENT BY 1;

-- 1
CREATE OR REPLACE FUNCTION GetUserRentalCount(p_UserID IN NUMBER) RETURN NUMBER IS
    v_Count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_Count FROM Rentals WHERE UserID = p_UserID;
    RETURN v_Count;
END;
/

-- 2
CREATE OR REPLACE FUNCTION EstimateCost(p_TariffID IN NUMBER, p_Minutes IN NUMBER) RETURN NUMBER IS
    v_Unlock NUMBER;
    v_MinPrice NUMBER;
BEGIN
    SELECT UnlockPrice, MinutePrice INTO v_Unlock, v_MinPrice FROM Tariffs WHERE TariffID = p_TariffID;
    RETURN v_Unlock + (v_MinPrice * p_Minutes);
END;
/

-- 3
CREATE OR REPLACE FUNCTION BatteryLabel(p_Level IN NUMBER) RETURN VARCHAR2 IS
BEGIN
    IF p_Level < 20 THEN RETURN 'Низкий';
    ELSIF p_Level < 70 THEN RETURN 'Средний';
    ELSE RETURN 'Высокий';
    END IF;
END;
/

-- 4
CREATE OR REPLACE FUNCTION CanUserRent(p_UserID IN NUMBER) RETURN NUMBER IS
    v_Bal NUMBER;
BEGIN
    SELECT Balance INTO v_Bal FROM Users WHERE UserID = p_UserID;
    IF v_Bal > 0 THEN RETURN 1; ELSE RETURN 0; END IF;
END;
/

-- 5
CREATE OR REPLACE FUNCTION GetActiveRentalID(p_UserID IN NUMBER) RETURN NUMBER IS
    v_ID NUMBER;
BEGIN
    SELECT RentalID INTO v_ID FROM Rentals 
    WHERE UserID = p_UserID AND RentalStatus = 'активно' AND ROWNUM = 1;
    RETURN v_ID;
EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL;
END;
/

-- 1
CREATE OR REPLACE PROCEDURE StartRental(p_UserID IN NUMBER, p_VehicleID IN NUMBER) IS
    v_Price NUMBER;
BEGIN
    SELECT t.MinutePrice INTO v_Price FROM Vehicles v JOIN Tariffs t ON v.TariffID = t.TariffID WHERE v.VehicleID = p_VehicleID;
    UPDATE Vehicles SET Status = 'бронь' WHERE VehicleID = p_VehicleID;
    INSERT INTO Rentals (UserID, VehicleID, FixedMinutePrice, RentalStatus)
    VALUES (p_UserID, p_VehicleID, v_Price, 'активно');
    COMMIT;
END;
/

-- 2
CREATE OR REPLACE PROCEDURE EndRental(
    p_RentalID IN NUMBER, 
    p_Lat IN NUMBER, 
    p_Lon IN NUMBER
) IS
    v_minutes NUMBER;
    v_start TIMESTAMP;
    v_price NUMBER;
BEGIN
    -- Получаем данные аренды
    SELECT StartTime, FixedMinutePrice 
    INTO v_start, v_price
    FROM Rentals 
    WHERE RentalID = p_RentalID;
    
    -- РАСЧЁТ МИНУТ: (текущее время - время старта) в днях * 24 * 60
    -- Используем CAST в DATE для простой арифметики
    v_minutes := ROUND(
        (CAST(CURRENT_TIMESTAMP AS DATE) - CAST(v_start AS DATE)) * 24 * 60
    );
    
    -- Если прошло меньше минуты - всё равно считаем как 1 минуту
    IF v_minutes < 1 THEN
        v_minutes := 1;
    END IF;
    
    -- Обновляем аренду с правильной стоимостью
    UPDATE Rentals 
    SET EndTime = CURRENT_TIMESTAMP, 
        RentalStatus = 'завершено',
        TotalCost = v_minutes * v_price
    WHERE RentalID = p_RentalID;

    -- Возвращаем транспорт на парковку
    UPDATE Vehicles 
    SET Status = 'доступно', 
        Lat = p_Lat, 
        Lon = p_Lon 
    WHERE VehicleID = (SELECT VehicleID FROM Rentals WHERE RentalID = p_RentalID);
    
    COMMIT;
    
    -- Для отладки
    DBMS_OUTPUT.PUT_LINE('Аренда ' || p_RentalID || 
                        ', минут: ' || v_minutes || 
                        ', цена минуты: ' || v_price || 
                        ', итого: ' || (v_minutes * v_price));
END;
/

-- 3
CREATE OR REPLACE PROCEDURE AddBalance(p_UserID IN NUMBER, p_Amount IN NUMBER) IS
BEGIN
    UPDATE Users SET Balance = Balance + p_Amount WHERE UserID = p_UserID;
    COMMIT;
END;
/

-- 4
CREATE OR REPLACE PROCEDURE RegisterUser(p_Name IN VARCHAR2, p_Email IN VARCHAR2, p_Phone IN VARCHAR2, p_RoleID IN NUMBER) IS
BEGIN
    INSERT INTO Users (FullName, Email, Phone, RoleID) VALUES (p_Name, p_Email, p_Phone, p_RoleID);
    COMMIT;
END;
/

-- 5
CREATE OR REPLACE PROCEDURE SetVehicleMaintenance(p_VehicleID IN NUMBER) IS
BEGIN
    UPDATE Vehicles SET Status = 'ремонт' WHERE VehicleID = p_VehicleID;
    COMMIT;
END;
/

CREATE OR REPLACE TRIGGER AFTER_RENTAL_END
AFTER UPDATE OF TotalCost ON Rentals
FOR EACH ROW
WHEN (NEW.RentalStatus = 'завершено')
BEGIN
    UPDATE Users 
    SET Balance = Balance - :NEW.TotalCost 
    WHERE UserID = :NEW.UserID;
END;
/

UPDATE Rentals 
SET TotalCost = 100 
WHERE RentalID = (SELECT RentalID FROM Rentals WHERE RentalStatus = 'завершено' FETCH FIRST 1 ROW ONLY);
COMMIT;

SELECT Balance FROM Users WHERE Email = 'kuliashov200@mail.ru';

CREATE USER testus IDENTIFIED BY 1111;
GRANT CONNECT, RESOURCE TO testus;



-- DELETE FROM Rentals;
-- DELETE FROM Vehicles;
-- DELETE FROM Users;
-- DELETE FROM Tariffs;
-- DELETE FROM VehicleModels;
-- DELETE FROM Roles;
-- COMMIT;

DROP TRIGGER AFTER_RENTAL_END;
DROP PROCEDURE StartRental;
DROP PROCEDURE EndRental;
DROP PROCEDURE AddBalance;
DROP PROCEDURE RegisterUser;
DROP PROCEDURE SetVehicleMaintenance;
DROP FUNCTION GetUserRentalCount;
DROP FUNCTION EstimateCost;
DROP FUNCTION BatteryLabel;
DROP FUNCTION CanUserRent;
DROP FUNCTION GetActiveRentalID;
DROP SEQUENCE ContractNumber;
DROP VIEW AvailableVehicles;
DROP INDEX IX_Users_Email;
DROP TABLE Rentals;
DROP TABLE Vehicles;
DROP TABLE Tariffs;
DROP TABLE Users;
DROP TABLE VehicleModels;
DROP TABLE Roles;