DROP TABLE CompanyStructure CASCADE CONSTRAINTS;

CREATE TABLE CompanyStructure (
    EmployeeID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FullName VARCHAR2(100) NOT NULL,
    Position VARCHAR2(50),
    ParentID NUMBER,
    CONSTRAINT FK_Manager FOREIGN KEY (ParentID) REFERENCES CompanyStructure(EmployeeID)
);

CREATE OR REPLACE PROCEDURE ShowSubordinates(p_ManagerID IN NUMBER) IS
BEGIN
    FOR r IN (
        SELECT 
            LEVEL as lvl, 
            LPAD(' ', (LEVEL-1)*4) || FullName as Name, 
            Position
        FROM CompanyStructure
        START WITH EmployeeID = p_ManagerID
        CONNECT BY PRIOR EmployeeID = ParentID
        ORDER SIBLINGS BY FullName
    ) LOOP
        DBMS_OUTPUT.PUT_LINE('Уровень ' || r.lvl || ': ' || r.Name || ' [' || r.Position || ']');
    END LOOP;
END;
/

CREATE OR REPLACE PROCEDURE AddEmployee(p_ParentID NUMBER, p_Name VARCHAR2, p_Pos VARCHAR2) IS
BEGIN
    INSERT INTO CompanyStructure (FullName, Position, ParentID)
    VALUES (p_Name, p_Pos, p_ParentID);
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE MoveTeam(p_OldManagerID NUMBER, p_NewManagerID NUMBER) IS
BEGIN
    UPDATE CompanyStructure
    SET ParentID = p_NewManagerID
    WHERE ParentID = p_OldManagerID;
    COMMIT;
END;
/

INSERT INTO CompanyStructure (FullName, Position, ParentID) 
VALUES ('Рауба Арсений', 'Генеральный директор', NULL);
CALL AddEmployee(1, 'Старовойтов тех. директор', 'Технический директор');
CALL AddEmployee(1, 'Статько оп. директор', 'Операционный директор');
CALL AddEmployee(2, 'Лужецкий механик', 'Старший механик');
CALL AddEmployee(2, 'Дмитроченко акб', 'Специалист по АКБ');
EXEC ShowSubordinates(1);
CALL MoveTeam(2, 3);



DROP PROCEDURE MoveTeam;
DROP PROCEDURE AddEmployee;
DROP PROCEDURE ShowSubordinates;
DROP TABLE CompanyStructure;